# Generated by Django 5.2.13 on 2026-04-22 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '小说分类',
                'verbose_name_plural': '小说分类',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='小说标题')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('description', models.TextField(verbose_name='简介')),
                ('word_count', models.IntegerField(default=0, verbose_name='字数')),
                ('update_status', models.CharField(blank=True, max_length=20, verbose_name='更新状态')),
                ('source', models.CharField(max_length=100, verbose_name='来源')),
                ('platform', models.CharField(max_length=50, verbose_name='平台')),
                ('clicks', models.IntegerField(default=0, verbose_name='点击数')),
                ('collects', models.IntegerField(default=0, verbose_name='收藏数')),
                ('recommends', models.IntegerField(default=0, verbose_name='推荐数')),
                ('last_chapter', models.CharField(blank=True, max_length=200, verbose_name='最新章节')),
                ('crawl_time', models.DateTimeField(verbose_name='爬取时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='novels.category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '小说',
                'verbose_name_plural': '小说',
                'db_table': 'novels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NovelAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_score', models.FloatField(default=0.0, verbose_name='情感得分')),
                ('hot_score', models.FloatField(default=0.0, verbose_name='热度评分')),
                ('quality_score', models.FloatField(default=0.0, verbose_name='质量评分')),
                ('category_popularity', models.IntegerField(default=0, verbose_name='分类热度排名')),
                ('word_count_level', models.CharField(max_length=20, verbose_name='字数级别')),
                ('analysis_time', models.DateTimeField(auto_now_add=True, verbose_name='分析时间')),
                ('novel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='novels.novel', verbose_name='小说')),
            ],
            options={
                'verbose_name': '小说分析',
                'verbose_name_plural': '小说分析',
                'db_table': 'novel_analysis',
            },
        ),
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(max_length=50, verbose_name='推荐类型')),
                ('score', models.FloatField(default=0.0, verbose_name='推荐得分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='推荐时间')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.novel', verbose_name='推荐小说')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '推荐日志',
                'verbose_name_plural': '推荐日志',
                'db_table': 'recommendation_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.novel', verbose_name='小说')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户收藏',
                'verbose_name_plural': '用户收藏',
                'db_table': 'user_collections',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'novel')},
            },
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, verbose_name='评分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评分时间')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.novel', verbose_name='小说')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户评分',
                'verbose_name_plural': '用户评分',
                'db_table': 'user_ratings',
                'unique_together': {('user', 'novel')},
            },
        ),
    ]
